export interface createSubModuleDto{
    id : number,
	name : string,
	code : string,
	view : boolean,
	create : boolean,
	edit : boolean,
	delete : boolean,
	print : boolean,
	authorize : boolean,
	unAuthorize : boolean,
	ctq : boolean,
	cto : boolean,
	ctdn : boolean,
	cti : boolean,
	date : boolean,
	mmId : number,
}